name: FastMinecart
version: '2.0.0'
main: ink.magma.fastminecart.FastMinecart
api-version: '1.21'
libraries:
  - io.github.revxrsal:lamp.common:4.0.0-rc.12
  - io.github.revxrsal:lamp.bukkit:4.0.0-rc.12
  - io.github.revxrsal:lamp.brigadier:4.0.0-rc.12
